[Output]
Format=directory
Output=bootloader
SplitArtifacts=

[Content]
Bootloader=none
Bootable=false
WithRecommends=no
WithDocs=no
# rdi-installer is to get the version number for the boot menu entry
Packages=
	shim
	systemd-boot
	rdi-installer
