[Content]
RootPassword=rdiinstaller
#Autologin=yes
Hostname=rdi-installer
Bootloader=none
Bootable=false
Timezone=UTC
Keymap=us
Locale=C.UTF-8
KernelCommandLine=quiet systemd.show_status=yes
Ssh=no
WithRecommends=no
WithDocs=no
# Trim down kernel modules
KernelModules=kernel/ -/sound/ -/parport/ -/pcmcia/ -floppy -pata-* -memstick/ 
Packages=
	aaa_base
	bash
	busybox-adduser
	busybox-bind-utils
	ca-certificates
	ca-certificates-mozilla
	coreutils
	coreutils-systemd
	efibootmgr
	glibc
	glibc-locale-base
	gpg2
	gptfdisk
	iproute2
	iputils
	kernel-default
	kernel-firmware-amdgpu
	kernel-firmware-network
	kernel-firmware-usb-network
	less
	libnss_usrfiles2
	libseccomp2
	login_defs
	mdadm
	openssh
	openSUSE-build-key
	openSUSE-release
	openSUSE-release-appliance-custom
	parted
	procps
	systemd
	systemd-networkd
	systemd-presets-branding-openSUSE
	systemd-resolved
	tar
	timezone
	udev
	vim-small
	wget
	rdi-installer
	rdi-installer-utilities
	rdii-helper
	shim
	systemd-boot
	update-bootloader
