#! /bin/bash

# Create new os-release
. /buildroot/usr/lib/os-release

cat <<EOF > /buildroot/usr/lib/os-release
NAME="Raw Disk Image Installer"
ID="raw-disk-image-installer"
VERSION_ID="${VERSION_ID}"
PRETTY_NAME="Raw Disk Image Installer (${VERSION_ID}-${IMAGE_VERSION})"
EOF

# Create new issue
cat <<EOF > /buildroot/usr/lib/issue.d/10-openSUSE.issue
Raw Disk Image Installer ${VERSION_ID}-${IMAGE_VERSION} - Kernel \r (\l).

EOF
